In [ ]:
import requests
from bs4 import BeautifulSoup
from datetime import datetime
import re

def generate_urls(type: str, offset: int=None):
    assert type in ['manga', 'anime'], 'Please provide `type` of either `manga` or `anime`'
    _url = f'https://myanimelist.net/top{type}.php'

    if offset is not None:
        assert offset % 50 == 0, 'Please provide offset in multiples of 50'
        _url = _url + f'?limit={offset}'

    res = requests.get(_url)
    soup = BeautifulSoup(res.text, 'html.parser')

    if type == 'anime':
        titles = soup.find_all('h3', class_='anime_ranking_h3')
        dates = soup.find_all('div', class_='information di-ib mt4')
        scores = soup.find_all('div', class_='js-top-ranking-score-col di-ib al')
        ranks = soup.find_all('span', class_='rank')
        member_divs = soup.find_all('div', class_='information di-ib mt4')
    else:
        titles = soup.find_all('h3', class_='manga_h3')
        dates = soup.find_all('div', class_='information di-ib mt4')
        scores = soup.find_all('div', class_ ='js-top-ranking-score-col di-ib al' )
        ranks = soup.find_all('span', class_ = 'rank')
        member_divs = soup.find_all('div', class_='information di-ib mt4')

    results = []
    for title, date, score, rank, member_div in zip(titles, dates, scores, ranks, member_divs):
        _title = title.a.contents
        _url = title.a.get('href')
        date_text = date.contents[2].strip()
        # Extract the first and last year from the date range if present
        years = re.findall(r'\b\d{4}\b', date_text)
        if len(years) == 2:
            start_date = datetime.strptime(years[0], '%Y').date()
            end_date = datetime.strptime(years[1], '%Y').date()
            _date = f"{start_date.strftime('%Y-%m')} - {end_date.strftime('%Y-%m')}"
        elif len(years) == 1:
            _date = datetime.strptime(years[0], '%Y').date().strftime('%Y-%m')
        else:
            _date = None

        _score = float(score.text.strip()) if score else None

        _rank = int(rank.text.strip()) if rank else None

        _members = None
        if member_div:
            member_text = member_div.get_text(strip=True)
            member_count_match = re.search(r'(\d{1,3}(?:,\d{3})*)(?=\s+members)', member_text)
            if member_count_match:
                # Extract the digits and remove any commas
                _members = int(member_count_match.group(1).replace(',', ''))

        results.append({
            'title': _title,
            'url': _url,
            'date_published': _date,
            'score': _score,
            'rank': _rank,
            'members': _members
        })

    continuation_token = soup.find_all('a', class_='next')
    if continuation_token:
        if offset is None:
            offset = 50
        else:
            offset = offset + 50
    else:
        offset = None

    return offset, results
offset, results = generate_urls('anime', offset=None)
for result in results:
    print(result)

{'title': ['Sousou no Frieren'], 'url': 'https://myanimelist.net/anime/52991/Sousou_no_Frieren', 'date_published': '2023-01 - 2024-01', 'score': 9.38, 'rank': 1, 'members': 699605}
{'title': ['Fullmetal Alchemist: Brotherhood'], 'url': 'https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood', 'date_published': '2009-01 - 2010-01', 'score': 9.09, 'rank': 2, 'members': 103338518}
{'title': ['Steins;Gate'], 'url': 'https://myanimelist.net/anime/9253/Steins_Gate', 'date_published': '2011-01 - 2011-01', 'score': 9.07, 'rank': 3, 'members': 112558850}
{'title': ['Gintama°'], 'url': 'https://myanimelist.net/anime/28977/Gintama°', 'date_published': '2015-01 - 2016-01', 'score': 9.06, 'rank': 4, 'members': 629513}
{'title': ['Shingeki no Kyojin Season 3 Part 2'], 'url': 'https://myanimelist.net/anime/38524/Shingeki_no_Kyojin_Season_3_Part_2', 'date_published': '2019-01 - 2019-01', 'score': 9.05, 'rank': 5, 'members': 192269840}
{'title': ['Gintama: The Final'], 'url': 'https://myanimelist.net/anime/39486/Gintama__The_Final', 'date_published': '2021-01 - 2021-01', 'score': 9.04, 'rank': 1, 'members': 149732}
{'title': ['Hunter x Hunter (2011)'], 'url': 'https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011', 'date_published': '2011-01 - 2014-01', 'score': 9.04, 'rank': 2, 'members': 142824019}
{'title': ["Gintama'"], 'url': 'https://myanimelist.net/anime/9969/Gintama', 'date_published': '2011-01 - 2012-01', 'score': 9.03, 'rank': 3, 'members': 555193}
{'title': ['Bleach: Sennen Kessen-hen'], 'url': 'https://myanimelist.net/anime/41467/Bleach__Sennen_Kessen-hen', 'date_published': '2022-01 - 2022-01', 'score': 9.02, 'rank': 4, 'members': 537292}
{'title': ['Ginga Eiyuu Densetsu'], 'url': 'https://myanimelist.net/anime/820/Ginga_Eiyuu_Densetsu', 'date_published': '1988-01 - 1997-01', 'score': 9.02, 'rank': 5, 'members': 321367}
{'title': ["Gintama': Enchousen"], 'url': 'https://myanimelist.net/anime/15417/Gintama__Enchousen', 'date_published': '2012-01 - 2013-01', 'score': 9.02, 'rank': 1, 'members': 324805}
{'title': ['Kaguya-sama wa Kokurasetai: Ultra Romantic'], 'url': 'https://myanimelist.net/anime/43608/Kaguya-sama_wa_Kokurasetai__Ultra_Romantic', 'date_published': '2022-01 - 2022-01', 'score': 9.01, 'rank': 2, 'members': 924450}
{'title': ['Fruits Basket: The Final'], 'url': 'https://myanimelist.net/anime/42938/Fruits_Basket__The_Final', 'date_published': '2021-01 - 2021-01', 'score': 8.98, 'rank': 3, 'members': 476155}
{'title': ['Gintama.'], 'url': 'https://myanimelist.net/anime/34096/Gintama', 'date_published': '2017-01 - 2017-01', 'score': 8.98, 'rank': 4, 'members': 314097}
{'title': ['Gintama'], 'url': 'https://myanimelist.net/anime/918/Gintama', 'date_published': '2006-01 - 2010-01', 'score': 8.94, 'rank': 5, 'members': 101063766}

In [ ]:
manga = []
anime = []

offset = None
type = 'manga'

while True:
    offset, _res = generate_urls(type=type, offset=offset)
    manga += _res
    print(f'{offset} {type} downloaded')
    if offset == 3000:
        break

offset = None
type = 'anime'

while True:
    offset, _res = generate_urls(type=type, offset=offset)
    anime += _res
    print(f'{offset} {type} downloaded')
    if offset == 3500:
        break

# Assuming manga and anime lists are filled with data, you can now create a dataset
import pandas as pd

manga_df = pd.DataFrame(manga, columns=['title', 'url', 'date_published', 'score', 'rank', 'members', 'type'])
anime_df = pd.DataFrame(anime, columns=['title', 'url', 'date_published', 'score', 'rank', 'members', 'type'])

# Example processing for sentiment analysis based on reviews (not real function)
def process_reviews(df):
    # Assuming you have a sentiment analysis function that processes reviews
    df['sentiment_score'] = df['reviews'].apply(sentiment_analysis_function)
    return df

# Processing reviews for manga and anime datasets
manga_df = process_reviews(manga_df)
anime_df = process_reviews(anime_df)

# Now you have two dataframes: manga_df and anime_df containing manga and anime data respectively

50 manga downloaded
100 manga downloaded
150 manga downloaded
200 manga downloaded
250 manga downloaded
300 manga downloaded
350 manga downloaded
400 manga downloaded
450 manga downloaded
500 manga downloaded
550 manga downloaded
600 manga downloaded
650 manga downloaded
700 manga downloaded
750 manga downloaded
800 manga downloaded
850 manga downloaded
900 manga downloaded
950 manga downloaded
1000 manga downloaded
1050 manga downloaded
1100 manga downloaded
1150 manga downloaded
1200 manga downloaded
1250 manga downloaded
1300 manga downloaded
1350 manga downloaded
1400 manga downloaded
1450 manga downloaded
1500 manga downloaded
1550 manga downloaded
1600 manga downloaded
1650 manga downloaded
1700 manga downloaded
1750 manga downloaded
1800 manga downloaded
1850 manga downloaded
1900 manga downloaded
1950 manga downloaded
2000 manga downloaded
2050 manga downloaded
2100 manga downloaded
2150 manga downloaded
2200 manga downloaded
2250 manga downloaded
2300 manga downloaded
2350 manga downloaded
2400 manga downloaded
2450 manga downloaded
2500 manga downloaded
2550 manga downloaded
2600 manga downloaded
2650 manga downloaded
2700 manga downloaded
2750 manga downloaded
2800 manga downloaded
2850 manga downloaded
2900 manga downloaded
2950 manga downloaded
3000 manga downloaded
50 anime downloaded
100 anime downloaded
150 anime downloaded
200 anime downloaded
250 anime downloaded
300 anime downloaded
350 anime downloaded
400 anime downloaded
450 anime downloaded
500 anime downloaded
550 anime downloaded
600 anime downloaded
650 anime downloaded
700 anime downloaded
750 anime downloaded
800 anime downloaded
850 anime downloaded
900 anime downloaded
950 anime downloaded
1000 anime downloaded
1050 anime downloaded
1100 anime downloaded
1150 anime downloaded
1200 anime downloaded
1250 anime downloaded
1300 anime downloaded
1350 anime downloaded
1400 anime downloaded
1450 anime downloaded
1500 anime downloaded
1550 anime downloaded
1600 anime downloaded
1650 anime downloaded
1700 anime downloaded
1750 anime downloaded
1800 anime downloaded
1850 anime downloaded
1900 anime downloaded
1950 anime downloaded
2000 anime downloaded
2050 anime downloaded
2100 anime downloaded
2150 anime downloaded
2200 anime downloaded
2250 anime downloaded
2300 anime downloaded
2350 anime downloaded
2400 anime downloaded
2450 anime downloaded
2500 anime downloaded
2550 anime downloaded
2600 anime downloaded
2650 anime downloaded
2700 anime downloaded
2750 anime downloaded
2800 anime downloaded
2850 anime downloaded
2900 anime downloaded
2950 anime downloaded
3000 anime downloaded
3050 anime downloaded
3100 anime downloaded
3150 anime downloaded
3200 anime downloaded
3250 anime downloaded
3300 anime downloaded
3350 anime downloaded
3400 anime downloaded
3450 anime downloaded
3500 anime downloaded

KeyError: 'reviews'

In [ ]:
pip install textblob

Requirement already satisfied: textblob in /usr/local/lib/python3.10/dist-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.10/dist-packages (from textblob) (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob) (1.4.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob) (2023.12.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob) (4.66.2)

In [ ]:
from textblob import TextBlob
import requests
from bs4 import BeautifulSoup

def download_reviews_with_sentiment(url: str, offset: int = None):
    reviews_with_sentiment = []
    try:
        while True:
            review_url = f'{url}/reviews'
            if offset is not None:
                review_url += f'?p={offset}'

            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
            }
            response = requests.get(review_url, headers=headers)
            response.raise_for_status()

            soup = BeautifulSoup(response.text, 'html.parser')
            review_divs = soup.find_all('div', class_='text')

            if not review_divs:
                break

            for review_div in review_divs:
                review_text = review_div.get_text().strip()
                sentiment_score = TextBlob(review_text).sentiment.polarity
                reviews_with_sentiment.append({
                    'review_text': review_text,
                    'sentiment_score': sentiment_score
                })

            next_page_link = soup.find('a', attrs={'data-ga-click-type': 'review-more-reviews'})
            if next_page_link:
                offset = offset + 1 if offset is not None else 2
            else:
                break

    except Exception as e:
        print(f'Error in download_reviews_with_sentiment: {e}')

    return reviews_with_sentiment

In [ ]:
def enrich_with_sentiment_scores(items):
    for idx, item in enumerate(items):
        offset = None
        item_reviews_with_sentiment = []

        try:
            # Download reviews with sentiment scores
            while True:
                reviews_with_sentiment = download_reviews_with_sentiment(item['url'], offset=offset)
                if not reviews_with_sentiment:
                    break

                item_reviews_with_sentiment.extend(reviews_with_sentiment)

                # Move to the next page if available
                offset = offset + 1 if offset is not None else 2

            # Calculate average sentiment score
            sentiment_scores = [review['sentiment_score'] for review in item_reviews_with_sentiment]
            average_sentiment_score = sum(sentiment_scores) / len(sentiment_scores) if sentiment_scores else None

            # Update item with reviews and average sentiment score
            item['reviews'] = {
                'reviews_with_sentiment': item_reviews_with_sentiment,
                'average_sentiment_score': average_sentiment_score
            }

        except Exception as e:
            print(f'Error processing item {idx}: {e}')

        if idx >= 2:
            break  # Limiting to enrich sentiment for a few items for demonstration

In [ ]:
# Check DataFrame structure
print(dataset.head())

# Debug download_reviews_with_sentiment for a sample URL
sample_url = 'https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood'
reviews_with_sentiment = download_reviews_with_sentiment(sample_url)
print(reviews_with_sentiment)

# Inspect sentiment scores for a few review texts
for review in reviews_with_sentiment:
    print(f"Review: {review['review_text']} | Sentiment Score: {review['sentiment_score']}")

# Debug enrich_with_sentiment_scores for a few items
sample_items = manga[:3]  # Process a subset of items for testing
enrich_with_sentiment_scores(sample_items)

# Print updated reviews for sample items
for item in sample_items:
    print(item['reviews'])

                                               title  \
0                                          [Berserk]
1  [JoJo no Kimyou na Bouken Part 7: Steel Ball Run]
2                                         [Vagabond]
3                                        [One Piece]
4                                          [Monster]

                                                 url     date_published  \
0            https://myanimelist.net/manga/2/Berserk            1989-01
1  https://myanimelist.net/manga/1706/JoJo_no_Kim...  2004-01 - 2011-01
2         https://myanimelist.net/manga/656/Vagabond  1998-01 - 2015-01
3         https://myanimelist.net/manga/13/One_Piece            1997-01
4            https://myanimelist.net/manga/1/Monster  1994-01 - 2001-01

   score  rank  members   type
0   9.47     1   690508  manga
1   9.30     2   265638  manga
2   9.25     3   382296  manga
3   9.22     4   618076  manga
4   9.16     5   245498  manga

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

Review: Unlike the 2003 adaptation, Brotherhood is a faithful representation of Arakawa Hiromu's manga.

Fullmetal Alchemist: Brotherhood is starting at a breakneck pace. However, once you get used to it, the pacing feels very appropriate for the series and only seems to increase the suspense. Brotherhood always manages to switch between serious and comedy. Interestingly, one of the greatest advantages of Brotherhood is actually its wealth of interesting characters. The original FMA focused primarily on the two main characters and their efforts to regain their bodies, while Brotherhood also explores other characters in great detail at the same time.

One of the many good things about this series
                  ...
is that there is no infill at all (yes, I'm thinking of Naruto etc), which keeps the story from losing momentum. All the episodes are concise and each scene is important as part of the huge main story.

The art is in a different style, a bit simpler, but that's not a bad thing. What is lacking in detail, it makes up for with some premier fight sequences. The animation is generally very neat and the movements of the characters are very fluid and natural.

The voice acting is excellent and consistent, and I think pretty much all of the characters have voice actors to suit their personalities. With such a cast of actors, you wouldn't expect less. Most opening / ending are fun to listen to.

You'd be hard pressed to find a shonen anime that will entertain you as much as Fullmetal Alchemist: Brotherhood. Really good anime, there is no other way to describe it. A must have for newcomers to anime and hardened otakus. | Sentiment Score: 0.2593201754385965
Review: I just finished FMAB and I have to say it was so well made. Most of the character was flushed out and had their backstories and goals. The world building was so vast and expansive you can do a whole analysis on that such as the cultures, people, beliefs, and nations. The themes Fullmetal explored was also fantastic such as war, man's inhumanity to man , personal struggle the characters faced, and understanding morality. The author of Fullmetal really put a lot of effort into making Fullmetal. The art, animation, and music was a big plus for this anime also. The comedy in this anime
                  ...
was well done and funny as hell, the funniest anime I have ever watched. The tone and the vibe was very nice also, at times it would get dark but I would be lifted by the comedy. But at times they mixed the comedy with the fights which was suppose to be serious and dark. The story was well done and nothing seemed out of place or didn't make sense.

The fights were confusing at times, half the time in the fights the good guys and bad guys were talking too each other way too much and other times they wont even talk and just start fighting. Another things is the pacing, I felt like the creators should have done a better job on shedding Ed's and Al's younger years and their troubles when they first joined the military and also the other characters also. My last problem was the consistency such as keeping the same music people enjoy alot to become a nostalgia for example keeping the same opening instead of it changing every time. And also doing a better job of making the audience care for the characters by doing a better job on the emotional scenes, their origins, and their dialogue.

So overall I enjoyed the show, it wasn't a masterpiece to say oh I will remember this show for the rest of my life, or bad to say that I'm never going to watch this show again . FMAB put a lot of passion into the visuals, story, and music which was a big plus because I enjoyed those aspects alot. But I think they could have done a better job in certain scenes and could have made the characters even more interesting and memorable then where they are right now. | Sentiment Score: 0.12836956521739132
Review: Number one on this site for a good reason. A show with fantastic music, very solid animation and character design, many loveable characters, a very satisfying story, and an emotional heart matched by few others. Not much to be said that hasn't already been said. Fullmetal Alchemist: Brotherhood provides an incredibly interesting world with a good magic system that is integrated into the story very well. I particularly enjoyed the fraternal bond between the two main characters that drove the story throughout, which helps to ground the story given the huge cast of supporting characters. The thematic content dealing with war, revenge, and family gave
                  ...
the story an interesting message that gives good thematic grounding to the setting. Also, the dub voice acting is great, providing fitting, distinct, and memorable voices for the vast array of characters, so for anyone who prefers dub, this anime is a solid choice. Highly recommended. | Sentiment Score: 0.3080952380952381
Review: The ending made me ball, watched it over the course of 4 months with my close friend and I enjoyed learning and connecting with the characters. Please take time out of your day or week or month or year to watch this. Absolute masterpiece.

Easily the best part is the relationship between the brothers but the foreshadowing is excellent too and each section is distinct and has new and interesting reoccurring characters.

I cannot recommend this show enough. It deserves the #1 place for sure even though it may not be my personal favorite of all time. It has all the right emotions. | Sentiment Score: 0.4119547119547119
Review: Fmab is really perfect and balanced in each and every aspect whether it may it's story,art style,music,characters and the level of enjoyment. Below I have explained the main aspects that I personally like about Fmab

(1)Story:The story is amazing and also the way it is structured is mind blowing and what I like most about Fmab is it's masterpiece storytelling layer after layer, it makes you engaged each and every second of it. It's just incredible how adventurous you feel when go through the journey of two brothers sometime you will feel the same feelings as of two brothers. The story is really a adventurous
                  ...
masterpiece. Also it has set many benchmarks in the shounen genre. The adventurous story is the second main reason why I love Fmab so much.

(2)Art style: Fmab is blessed with perfect word building. It's word building is as vibrant as it's characters. The word building perfectly sets with the main theme of Fmab.

(3)Characters: Well what's the speciality of Fmab and why do you need to watch?The answer to this question is characters. Introducing these much characters and giving them their own importance in the story and structure in only 64 episodes is just incredible. You will surely sympathize and like all the characters of Fmab whether it may protagonist or antagonist or side characters. Really characters of Fmab are unique in their own way who has their own importance in the story and are deeply connected to each other like a circle. The main reason why I love Fmab so much is it's characters | Sentiment Score: 0.3848039215686273
Review: *REVIEW FOR FULLMETAL ALCHEMIST: BROTHERHOOD*
Story (10/10):
In my opinion, FMA:B has one of the greatest stories of anime. Based in a fictional country within a law with its own physics rules (alchemy), the series successfully manages to keep the viewer wanting more and more episodes. This aspect is also completed by the main characters' goals (return to the original bodies and .... (here's a spoiler so nah))

Animation & Art (8/10):
The animation deserves a 7/10 but thanks to the beautiful art of the series, I think it deserves overall an 8/10 on this criterion. They knew how to add symbolism to the story, a very important
                  ...
detail in my opinion. Also although the animation isn't great, the shots are amazing.

Sound, Voice Acting & Music (10/10):
Everything in this criterion is a 10/10. The soundtracks? Excellent. The voice acting? Great. The openings/endings? Legendary.

Character (10/10):
The characters are not well-built. They are "legendary-built". The character development is one of the things that will impress you regarding the character as you advance further in the story. There are also a lot of characters that from villains turn to heroes, and from heroes turn to villains, an interesting detail that you don't want to miss.

Overall, Fullmetal Alchemist: Brotherhood is an ABSOLUTELY must-watch for all anime enthusiasts. Although the first 10 episodes are weak, give it a try and I assure you the final quarter is LEGENDARY.

Recommendable only to anime enthuasists? : No.
Genre: Action, Drama, Adventure. | Sentiment Score: 0.3912222222222222
Review: To begin with, Fullmetal Alchemist: Brotherhood is my favorite anime. I had mixed feelings watching, I laughed and I cried, the narrative is very well developed, the characters have a good development too and the soundtrack is beautiful, really, a lot of the feelings you have watching are because of the soundtrack .
The animation is good, but in many scenes it loses its quality, but in important moments it is absurdly fantastic. The mood timing is very good.
And the ending is spectacular & lt; 3
the only problems for me are a few ruined episodes in the beginning and the little twist that happens in the
                  ...
final arc.

I recommend! | Sentiment Score: 0.3196052631578948
Review: From the beginning, the anime is slowly building up to the end of the series. It can feel a bit slow and pointless at certain points but I still believe it has a much more focused pace and plot than the majority of other shonen. The build up works well at developing characters that actually have character, distinct characters that you remember and actually care about. Many elements of FMA brotherhood can be compared to other shonen such as Naruto, and FMA brotherhood pulls these elements off much better than Naruto and the others. The story was conclusive and ending satisfying.

If you want a
                  ...
focused shonen that doesn't go 1000 different directions and doesn't have an infinitely powerscaling main character that eventually has to fight galactic beings or the strongest beings from other universes, then watch this.

9/10 pretty good | Sentiment Score: 0.12662907268170426
Review: one of best anime in the history of anime. period.

plot is amazing, characters are well-developed, and the soundtrack is stunning. there is not a single boring moment in this show, and it brought me so much laughter and tears. absolutely touching story of two brothers and their journey of self-discovery. the way this show portrayed alchemy is something very refreshing too, and delves into the themes of sacrifice and exchange. although this is a fantastical show, many of the lessons learned and themes explored are applicable in real life too.

all in all, a beautiful masterpiece that all anime fans should watch. whether you like
                  ...
it or not, you will take away something from this show. | Sentiment Score: 0.36688311688311687
Review: FMAB might be the perfect anime.

Story: 10

The writing in this anime is beyond phenomenal. It keeps you engaged, and it leaves you wanting more. It manages to communicate its philosophies and its themes in a way that feels so impactful and meaningful.

Art: 9

I'm very tempted to give it a 10. The animation is crisp yet fluid, and I enjoy the art style a lot. The fight scenes are amazing.

...
Sound: 9

The first opening might be the greatest opening in anime of all time. And it's not even the only opening in this show I can say that about. Enough said.

Character: 10

This might be the show's greatest strength. The characters are all complex and layered with personality, ideals, and motivations. Edward and Alphonse are the driving force behind this show, but they aren't the only great characters. Winry, Roy Mustang, and especially Hohenheim are all some of my favorite characters, period. What's more, the antagonists are also absolutely outstanding.

Enjoyment: 10

I love this show so much. It is so well-written, so well-produced, and just off of the merits of its quality alone, managed to earn a 10 in enjoyment.

Overall: 10

What can I say? I can't find a single fault. Not one crack, in 64 episodes. It's phenomenal. It's way too good. It might be one of the best TV shows, not just one of the best anime. | Sentiment Score: 0.38801843317972345
Review: I will say that the overall anime is pretty solid and a straight 9 . But indeed there are some arcs in the story that just feels its being dragged on.

Overall , the characters were well written , But 4 of them were written a little better than the others IMO , These are Mustang , Scar , King Bradley and Hohenhiem.

The music choices were good .

The Promised Day arc was probably the best overall , though at some point it felt like it was being dragged on.

The only flaw was before the promised day arc , Information is thrown
                  ...
at you like a bullet train , and the pacing of the story felt rushed.

Overall , A Solid 9/10 . A great story with brilliant execution . | Sentiment Score: 0.2775
Review: I actually never had a thought of watching this anime but when i got to know that this is the most high rated anime on imdb i had a curosity to check, is it actually good has people rated it, did it deserve the spot and omg when i finished i thought wish it had some more episodes u can barely hate any charcters had well written villans a mc with no demon inside him shit the mc didnt even got any power up but still his charcters was good asf it also shows that not everytime u need a overpowered mc to make an
                  ...
anime popular i didnt got bore in any ep of this anime idk about the fma havent watched it yet but for me this anime is 10/10 and also it had good satisfying and best ending in any anime for me  expect for code geass | Sentiment Score: 0.3633333333333333
Review: This show, I dont even know where to begin with it. Wow. Just, wow.

Very few shows would I rate a 10, in fact as of right now, this is the only one that qualifies in my mind. Whether it really is the perfect show doesn't really matter because it is to me.

I first watched Fullmetal two years ago and I was struck by a colourful cast of characters, an intriguing story and a crippling anime addiction. The pacing is incredible, the romance is believable, and doesn't get in the way of the storytelling. I don't cry much, especially not for background characters, but when
                  ...
I tell you I cried watching this show I CRIED. (In a good way of course!)

Another thing I love is the small details sprinked throughout the show, some that I hadn't even noticed until the second time through.

In conclusion: WATCH THIS SHOW. DO IT. | Sentiment Score: 0.2765126050420168
Review: [POSSIBLE SPOILERS]

Fullmetal Alchemist Brotherhood is undoubtedly one of the best shonen anime.

Story
The story starts off when the main character Edward Elric and Alphonse Elric wanted to resurrect their deceased mother but since the human transmutation backfired, it costed Edward's leg and Alphonse's body. Edward realised that he made a huge mistake so he made a deal with The Truth (God of transmutation) to big
                  ...
back his brother Alphonse and that costed his arm. The story then continues when Edward burns down the house that him and his brother lived in so that they cannot turn back and are forced on the journey to get their original bodies back. They joined the military to accomplish their goals but not to participate in brutal, genocidal campaigns to generate a Philosophers Stone from the people they killed. Of course, the military get complicated throughout the series as it gets corrupted by evil immortal devils using Philosophers Stone to create an immortal army of alien-like creatures. The story overall is interesting and written well throughout the series.
10/10

Art
The general art and animation for an anime adaptation from 2009 is impressive, it has high definition and high framed action scenes with simple colours palette used to light up the world. The simplistic colour palette gives the look of the early 1900s matching the general theme of the show.
9/10

Characters
Fullmetal Alchemist Brotherhood introduced many side and minor characters are in the show in a steady pace. All the characters have depth and a reason why they exist in the show especially the main characters. The main characters changed a lot from the start like how childish Edward was eagerly trying to bring back his brother till the end when he realised the truth about the military and prioritised others lives over their own body.
10/10

Enjoyment + Overall
I surprisingly enjoyed it despite the fact that I almost dropped the show. The show started off really slow paced because it developed the general background information of how alchemy worked prior the development of the main characters. It was a smart way to engage me more into the characters with a little background knowledge of what is alchemy. The show used its slow paced story to foreshadow future events and introduce new characters and give them depth. Overall, the anime is both extremely enjoyable and well written in every aspect of the show.
8/10

                                 [HIGHLY RECOMMENDED SHOW] | Sentiment Score: 0.06287369872191301
Review: What an anime!

It's one of the last animes I watched with my little brother. It holds a special place in my heart.

The story
The story is just insanely good. It shows you how much does it take to bring back the dead, and it fails. Nobody can bring the dead back to life. Not even the best alchemist in the world! It's seriously good. I was wanting more after the series was over, it's that good!

The art
The art style, in this anime, is great. It's one of those anime, where you don't care about the art styles, you care about the
                  ...
characters and the story, but jeeze! The art style compliments the series.

The sound
From what I can remember, the sound is really good!

The characters
You care about the characters, almost all of them. They are so good! It's like the best for character development.

The enjoyment
I throughly enjoyed this anime. It's so good! I was left speechless after it concluded.

The overall
Watch this anime if you haven't already. It's so good. Try it if you don't even like anime. It's that good! | Sentiment Score: 0.4132554945054945
Review: I really enjoyed the anime and think it's good. I was impressed with how it tricked me many times and always made sense. It was enjoyable but not enjoyable enough to be in my top 10 or something like that, and I see I don't enjoy it as much as most people. Still, really good anime.
The story was all connected and well built. It's impossible to say anything that happens, even the most minor detail, without spoiling so much, which might be why I barely ever see people talking about this anime.
Some of the best opening songs were used, Rain being one of my
                  ...
favourites of all time. USO, the first ending, was also really nice. The soundtracks also complimented the events very well.
My favourite characters are Ling and Hohenheim, and overall I really loved the characters. I was sad that Scar wasn't as good in my opinion as he is in FullMetal Alchemist though.
Final Score: 8/10 | Sentiment Score: 0.3213333333333333
Review: Just one word - Masterpiece !!!!!!!!!!!

This is my first review , please tell me if i lack anything -

FMAB deserves the praise it gets , most importantly people compare it with other animes and tend to say FMAB lacks this but in my opinion its just perfect .

First time i felt attach to so many characters , it was awesome not a single episode bored me.

If you are confused to watch it or not , i mean cmon man there shouldn't be option for skipping this legendary anime.


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
reviews_column = dataset['reviews']
reviews_column

KeyError: 'reviews'

In [ ]:
print(dataset.head())

                                               title  \
0                                          [Berserk]
1  [JoJo no Kimyou na Bouken Part 7: Steel Ball Run]
2                                         [Vagabond]
3                                        [One Piece]
4                                          [Monster]

                                                 url     date_published  \
0            https://myanimelist.net/manga/2/Berserk            1989-01
1  https://myanimelist.net/manga/1706/JoJo_no_Kim...  2004-01 - 2011-01
2         https://myanimelist.net/manga/656/Vagabond  1998-01 - 2015-01
3         https://myanimelist.net/manga/13/One_Piece            1997-01
4            https://myanimelist.net/manga/1/Monster  1994-01 - 2001-01

   score  rank  members   type
0   9.47     1   690508  manga
1   9.30     2   265638  manga
2   9.25     3   382296  manga
3   9.22     4   618076  manga
4   9.16     5   245498  manga

In [ ]:
anime_df = pd.DataFrame(anime)
manga_df = pd.DataFrame(manga)

anime_df['title'] = anime_df['title'].apply(lambda x: ''.join(x) if isinstance(x, list) else x)
manga_df['title'] = manga_df['title'].apply(lambda x: ''.join(x) if isinstance(x, list) else x)
anime_w_manga = pd.merge(anime_df, manga_df, on='title', how='inner', suffixes=('_anime', '_manga'))
anime_w_manga

,title,url_anime,date_published_anime,score_anime,rank_anime,members_anime,reviews_anime,url_manga,date_published_manga,score_manga,rank_manga,members_manga,reviews_manga
0,One Piece,https://myanimelist.net/anime/21/One_Piece,1999-01,8.72,1,2348773,NaN,https://myanimelist.net/manga/13/One_Piece,1997-01,9.22,4,618070,[Frequently categorized with both Bleach and N...
1,Kimi no Suizou wo Tabetai,https://myanimelist.net/anime/36098/Kimi_no_Su...,2018-01 - 2018-01,8.55,5,963905,NaN,https://myanimelist.net/manga/104538/Kimi_no_S...,2016-01 - 2017-01,8.50,3,743438,NaN
2,Slam Dunk,https://myanimelist.net/anime/170/Slam_Dunk,1993-01 - 1996-01,8.55,5,300582,NaN,https://myanimelist.net/manga/51/Slam_Dunk,1990-01 - 1996-01,9.09,1,170606,NaN
3,Grand Blue,https://myanimelist.net/anime/37105/Grand_Blue,2018-01 - 2018-01,8.43,1,777444,NaN,https://myanimelist.net/manga/70345/Grand_Blue,2014-01,9.03,4,176181,NaN
4,Natsume Yuujinchou,https://myanimelist.net/anime/4081/Natsume_Yuu...,2008-01 - 2008-01,8.31,4,539772,NaN,https://myanimelist.net/manga/1859/Natsume_Yuu...,2003-01,8.67,3,43952,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Spiral: Suiri no Kizuna,https://myanimelist.net/anime/341/Spiral__Suir...,2002-01 - 2003-01,7.22,3,352692,NaN,https://myanimelist.net/manga/534/Spiral__Suir...,1999-01 - 2005-01,7.96,5,512231,NaN
75,Mayo Chiki!,https://myanimelist.net/anime/10110/Mayo_Chiki,2011-01 - 2011-01,7.22,5,494485,NaN,https://myanimelist.net/manga/21860/Mayo_Chiki,2010-01 - 2013-01,7.68,2,323268,NaN
76,Accel World,https://myanimelist.net/anime/11759/Accel_World,2012-01 - 2012-01,7.21,3,714293,NaN,https://myanimelist.net/manga/23116/Accel_World,2009-01,7.76,3,9095,NaN
77,Hikikomari Kyuuketsuki no Monmon,https://myanimelist.net/anime/54103/Hikikomari...,2023-01 - 2023-01,7.19,1,395987,NaN,https://myanimelist.net/manga/138763/Hikikomar...,2020-01,7.60,2,1840,NaN
78,"Inari, Konkon, Koi Iroha.",https://myanimelist.net/anime/20457/Inari_Konk...,2014-01 - 2014-01,7.19,3,165618,NaN,https://myanimelist.net/manga/23689/Inari_Konk...,2010-01 - 2015-01,7.83,5,518133,NaN

In [ ]:
anime_row_count = len(anime_df)
anime_row_count

1050

In [ ]:
manga_row_count = len(manga_df)
manga_row_count

#Why is there 120 in each but goes down to 6 we combined.

900

In [ ]:
!pip install fuzzywuzzy
import pandas as pd
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

# Assuming anime_df and manga_df are your DataFrames
anime_df = pd.DataFrame(anime)
manga_df = pd.DataFrame(manga)

# Convert manga titles to strings
manga_df['title'] = manga_df['title'].astype(str)

# Define a threshold for string similarity
# This will determine how closely the titles need to match
threshold = 80

# Function to find best match for each title in anime_df
def find_best_match(title, choices):
    match, score = process.extractOne(str(title), choices, scorer=fuzz.token_sort_ratio)
    if score >= threshold:
        return match
    else:
        return None

# Create a list of unique titles from manga_df
manga_titles = manga_df['title'].unique().tolist()

# Apply the find_best_match function to anime_df['title'] and create a new column 'matched_title'
anime_df['matched_title'] = anime_df['title'].apply(lambda x: find_best_match(x, manga_titles))

# Merge anime_df and manga_df based on 'matched_title'
merged_df = pd.merge(anime_df, manga_df, left_on='matched_title', right_on='title', how='inner')

# Drop the 'matched_title' column if you don't need it in the final merged DataFrame
merged_df.drop('matched_title', axis=1, inplace=True)

# Display the resulting merged DataFrame
print(merged_df)

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

                                               title_x  \
0                                          [One Piece]
1    [Rurouni Kenshin: Meiji Kenkaku Romantan - Tsu...
2                    [Code Geass: Hangyaku no Lelouch]
3                                  [Violet Evergarden]
4                          [Kimi no Suizou wo Tabetai]
..                                                 ...
137             [Jinrui wa Suitai Shimashita Specials]
138                               [Kuroshitsuji Recap]
139               [Puchimas!!: Petit Petit iDOLM@STER]
140                                       [Re:Monster]
141             [Kono Bijutsu-bu ni wa Mondai ga Aru!]

                                                 url_x   date_published_x  \
0           https://myanimelist.net/anime/21/One_Piece            1999-01
1    https://myanimelist.net/anime/44/Rurouni_Kensh...  1999-01 - 1999-01
2    https://myanimelist.net/anime/1575/Code_Geass_...  2006-01 - 2007-01
3    https://myanimelist.net/anime/33352/Violet_Eve...  2018-01 - 2018-01
4    https://myanimelist.net/anime/36098/Kimi_no_Su...  2018-01 - 2018-01
..                                                 ...                ...
137  https://myanimelist.net/anime/15617/Jinrui_wa_...  2012-01 - 2013-01
138  https://myanimelist.net/anime/6163/Kuroshitsuj...  2009-01 - 2009-01
139  https://myanimelist.net/anime/21073/Puchimas__...  2014-01 - 2014-01
140     https://myanimelist.net/anime/56690/Re_Monster            2024-01
141  https://myanimelist.net/anime/31952/Kono_Bijut...  2016-01 - 2016-01

     score_x  rank_x  members_x reviews_x  \
0       8.72       1    2348773       NaN
1       8.70       4     276629       NaN
2       8.70       1   72247242       NaN
3       8.68       2  181777597       NaN
4       8.55       5     963905       NaN
..       ...     ...        ...       ...
137     7.19       5     319989       NaN
138     7.19       3     940170       NaN
139     7.18       5     148768       NaN
140     7.18       2      64187       NaN
141     7.17       3     304929       NaN

                                         title_y  \
0                                  ['One Piece']
1    ['Rurouni Kenshin: Meiji Kenkaku Romantan']
2         ['Code Geass: Hangyaku no Lelouch R2']
3                   ['Violet Evergarden Gaiden']
4                  ['Kimi no Suizou wo Tabetai']
..                                           ...
137              ['Jinrui wa Suitai Shimashita']
138                             ['Kuroshitsuji']
139              ['Puchimas!: Petit iDOLM@STER']
140                                  ['Monster']
141      ['Kono Bijutsubu ni wa Mondai ga Aru!']

                                                 url_y   date_published_y  \
0           https://myanimelist.net/manga/13/One_Piece            1997-01
1    https://myanimelist.net/manga/22/Rurouni_Kensh...  1994-01 - 1999-01
2    https://myanimelist.net/manga/107645/Code_Geas...  2008-01 - 2009-01
3    https://myanimelist.net/manga/113819/Violet_Ev...  2018-01 - 2018-01
4    https://myanimelist.net/manga/104538/Kimi_no_S...  2016-01 - 2017-01
..                                                 ...                ...
137  https://myanimelist.net/manga/24562/Jinrui_wa_...  2007-01 - 2014-01
138    https://myanimelist.net/manga/3866/Kuroshitsuji            2006-01
139  https://myanimelist.net/manga/29899/Puchimas__...            2008-01
140            https://myanimelist.net/manga/1/Monster  1994-01 - 2001-01
141  https://myanimelist.net/manga/50331/Kono_Bijut...            2012-01

     score_y  rank_y  members_y  \
0       9.22       4     618070
1       8.56       5     997806
2       7.57       4      91091
3       8.30       5     183246
4       8.50       3     743438
..       ...     ...        ...
137     7.76       4     142559
138     8.41       4     158814
139     7.72       5       1262
140     9.16       5     245492
141     7.72       4      22490

                                             reviews_y
0    [Frequently categorized with both Bleach and N...
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
137                                                NaN
138                                                NaN
139                                                NaN
140                                                NaN
141                                                NaN

[142 rows x 14 columns]

In [ ]:
merged_df

,title_x,url_x,date_published_x,score_x,rank_x,members_x,reviews_x,title_y,url_y,date_published_y,score_y,rank_y,members_y,reviews_y
0,[One Piece],https://myanimelist.net/anime/21/One_Piece,1999-01,8.72,1,2348773,NaN,['One Piece'],https://myanimelist.net/manga/13/One_Piece,1997-01,9.22,4,618070,[Frequently categorized with both Bleach and N...
1,[Rurouni Kenshin: Meiji Kenkaku Romantan - Tsu...,https://myanimelist.net/anime/44/Rurouni_Kensh...,1999-01 - 1999-01,8.70,4,276629,NaN,['Rurouni Kenshin: Meiji Kenkaku Romantan'],https://myanimelist.net/manga/22/Rurouni_Kensh...,1994-01 - 1999-01,8.56,5,997806,NaN
2,[Code Geass: Hangyaku no Lelouch],https://myanimelist.net/anime/1575/Code_Geass_...,2006-01 - 2007-01,8.70,1,72247242,NaN,['Code Geass: Hangyaku no Lelouch R2'],https://myanimelist.net/manga/107645/Code_Geas...,2008-01 - 2009-01,7.57,4,91091,NaN
3,[Violet Evergarden],https://myanimelist.net/anime/33352/Violet_Eve...,2018-01 - 2018-01,8.68,2,181777597,NaN,['Violet Evergarden Gaiden'],https://myanimelist.net/manga/113819/Violet_Ev...,2018-01 - 2018-01,8.30,5,183246,NaN
4,[Kimi no Suizou wo Tabetai],https://myanimelist.net/anime/36098/Kimi_no_Su...,2018-01 - 2018-01,8.55,5,963905,NaN,['Kimi no Suizou wo Tabetai'],https://myanimelist.net/manga/104538/Kimi_no_S...,2016-01 - 2017-01,8.50,3,743438,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,[Jinrui wa Suitai Shimashita Specials],https://myanimelist.net/anime/15617/Jinrui_wa_...,2012-01 - 2013-01,7.19,5,319989,NaN,['Jinrui wa Suitai Shimashita'],https://myanimelist.net/manga/24562/Jinrui_wa_...,2007-01 - 2014-01,7.76,4,142559,NaN
138,[Kuroshitsuji Recap],https://myanimelist.net/anime/6163/Kuroshitsuj...,2009-01 - 2009-01,7.19,3,940170,NaN,['Kuroshitsuji'],https://myanimelist.net/manga/3866/Kuroshitsuji,2006-01,8.41,4,158814,NaN
139,[Puchimas!!: Petit Petit iDOLM@STER],https://myanimelist.net/anime/21073/Puchimas__...,2014-01 - 2014-01,7.18,5,148768,NaN,['Puchimas!: Petit iDOLM@STER'],https://myanimelist.net/manga/29899/Puchimas__...,2008-01,7.72,5,1262,NaN
140,[Re:Monster],https://myanimelist.net/anime/56690/Re_Monster,2024-01,7.18,2,64187,NaN,['Monster'],https://myanimelist.net/manga/1/Monster,1994-01 - 2001-01,9.16,5,245492,NaN
141,[Kono Bijutsu-bu ni wa Mondai ga Aru!],https://myanimelist.net/anime/31952/Kono_Bijut...,2016-01 - 2016-01,7.17,3,304929,NaN,['Kono Bijutsubu ni wa Mondai ga Aru!'],https://myanimelist.net/manga/50331/Kono_Bijut...,2012-01,7.72,4,22490,NaN

In [ ]:
# Filter rows where start_year_y is before start_year_x
filtered_df = merged_df[merged_df['date_published_y'] < merged_df['date_published_x']]

filtered_df

,title_x,url_x,date_published_x,score_x,rank_x,members_x,reviews_x,title_y,url_y,date_published_y,score_y,rank_y,members_y,reviews_y
0,[One Piece],https://myanimelist.net/anime/21/One_Piece,1999-01,8.72,1,2348773,NaN,['One Piece'],https://myanimelist.net/manga/13/One_Piece,1997-01,9.22,4,618070,[Frequently categorized with both Bleach and N...
1,[Rurouni Kenshin: Meiji Kenkaku Romantan - Tsu...,https://myanimelist.net/anime/44/Rurouni_Kensh...,1999-01 - 1999-01,8.70,4,276629,NaN,['Rurouni Kenshin: Meiji Kenkaku Romantan'],https://myanimelist.net/manga/22/Rurouni_Kensh...,1994-01 - 1999-01,8.56,5,997806,NaN
4,[Kimi no Suizou wo Tabetai],https://myanimelist.net/anime/36098/Kimi_no_Su...,2018-01 - 2018-01,8.55,5,963905,NaN,['Kimi no Suizou wo Tabetai'],https://myanimelist.net/manga/104538/Kimi_no_S...,2016-01 - 2017-01,8.50,3,743438,NaN
5,[Slam Dunk],https://myanimelist.net/anime/170/Slam_Dunk,1993-01 - 1996-01,8.55,5,300582,NaN,['Slam Dunk'],https://myanimelist.net/manga/51/Slam_Dunk,1990-01 - 1996-01,9.09,1,170606,NaN
6,[Zoku Natsume Yuujinchou],https://myanimelist.net/anime/5300/Zoku_Natsum...,2009-01 - 2009-01,8.54,2,247988,NaN,['Natsume Yuujinchou'],https://myanimelist.net/manga/1859/Natsume_Yuu...,2003-01,8.67,3,43952,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,[Jinrui wa Suitai Shimashita Specials],https://myanimelist.net/anime/15617/Jinrui_wa_...,2012-01 - 2013-01,7.19,5,319989,NaN,['Jinrui wa Suitai Shimashita'],https://myanimelist.net/manga/24562/Jinrui_wa_...,2007-01 - 2014-01,7.76,4,142559,NaN
138,[Kuroshitsuji Recap],https://myanimelist.net/anime/6163/Kuroshitsuj...,2009-01 - 2009-01,7.19,3,940170,NaN,['Kuroshitsuji'],https://myanimelist.net/manga/3866/Kuroshitsuji,2006-01,8.41,4,158814,NaN
139,[Puchimas!!: Petit Petit iDOLM@STER],https://myanimelist.net/anime/21073/Puchimas__...,2014-01 - 2014-01,7.18,5,148768,NaN,['Puchimas!: Petit iDOLM@STER'],https://myanimelist.net/manga/29899/Puchimas__...,2008-01,7.72,5,1262,NaN
140,[Re:Monster],https://myanimelist.net/anime/56690/Re_Monster,2024-01,7.18,2,64187,NaN,['Monster'],https://myanimelist.net/manga/1/Monster,1994-01 - 2001-01,9.16,5,245492,NaN
141,[Kono Bijutsu-bu ni wa Mondai ga Aru!],https://myanimelist.net/anime/31952/Kono_Bijut...,2016-01 - 2016-01,7.17,3,304929,NaN,['Kono Bijutsubu ni wa Mondai ga Aru!'],https://myanimelist.net/manga/50331/Kono_Bijut...,2012-01,7.72,4,22490,NaN

In [ ]:
csv_filename = 'filtered_data.csv'
filtered_df.to_csv(csv_filename, index=False)